import ActionBar from "vuexp/src/core/components/ActionBar/ActionBar";
import ActionItem from "vuexp/src/core/components/ActionItem/ActionItem";
import NavigationButton from "vuexp/src/core/components/NavigationButton/NavigationButton";
import FormattedString from "vuexp/src/core/components/FormattedString/FormattedString";
import Frame from "vuexp/src/core/components/Frame/Frame";
import Switcher from "vuexp/src/core/components/Switcher/Switcher";
import Slider from "vuexp/src/core/components/Slider/Slider";
import TextView from "vuexp/src/core/components/TextView/TextView";
import Progress from "vuexp/src/core/components/Progress/Progress";
import SearchBar from "vuexp/src/core/components/SearchBar/SearchBar";
import SegmentedBar from "vuexp/src/core/components/SegmentedBar/SegmentedBar";
import SegmentedBarItem from "vuexp/src/core/components/SegmentedBarItem/SegmentedBarItem";
import Span from "vuexp/src/core/components/Span/Span";
import Button from "vuexp/src/components/VxpButton";
import DatePicker from "vuexp/src/components/VxpDatePicker";
import Img from "vuexp/src/components/VxpImage";
import Label from "vuexp/src/components/VxpLabel";
import ListView from "vuexp/src/components/VxpListView";
import TabView from "vuexp/src/core/components/TabView/TabView";
import TabViewItem from "vuexp/src/core/components/TabViewItem/TabViewItem";
import TextField from "vuexp/src/components/VxpTextField";
import ScrollView from "vuexp/src/core/components/ScrollView/ScrollView";
import WebView from "vuexp/src/core/components/WebView/WebView";
import Page from "vuexp/src/components/Page";
import AbsoluteLayout from "vuexp/src/layouts/AbsoluteLayout";
import DockLayout from "vuexp/src/layouts/DockLayout";
import FlexboxLayout from "vuexp/src/layouts/FlexboxLayout";
import GridLayout from "vuexp/src/layouts/GridLayout";
import StackLayout from "vuexp/src/layouts/StackLayout";
import WrapLayout from "vuexp/src/layouts/WrapLayout";
import ActionDialog from "vuexp/src/core/dialogs/ActionDialog";
import AlertDialog from "vuexp/src/core/dialogs/AlertDialog";
import ConfirmDialog from "vuexp/src/core/dialogs/ConfirmDialog";

import VxpButton from "vuexp/src/components/VxpButton";
import VxpCheckbox from "vuexp/src/components/VxpCheckbox";
import VxpDatePicker from "vuexp/src/components/VxpDatePicker";
import VxpDropDown from "vuexp/src/components/VxpDropDown";
import VxpDropDown2 from "vuexp/src/components/VxpDropDown2";
import VxpIconButton from "vuexp/src/components/VxpIconButton";
import VxpImage from "vuexp/src/components/VxpImage";

import VxpLabel from "vuexp/src/components/VxpLabel";
import VxpLink from "vuexp/src/components/VxpLink";
import VxpListView from "vuexp/src/components/VxpListView";
import VxpMultiSelectDropdown from "vuexp/src/components/VxpMultiSelectDropdown";
import VxpTableView from "vuexp/src/components/VxpTableView";
import VxpTextField from "vuexp/src/components/VxpTextField";
import VxpSideDrawer from "vuexp/src/components/VxpSideDrawer/VxpSideDrawer";
import VxpDropdownMenu from "vuexp/src/components/menus/VxpDropdownMenu";

export default function registerComponents(Vue) {
  Vue.component("Button", Button);
  Vue.component("DatePicker", DatePicker);
  Vue.component("Img", Img);
  Vue.component("Label", Label);
  Vue.component("ListView", ListView);
  Vue.component("Page", Page);
  Vue.component("Progress", Progress);
  Vue.component("ScrollView", ScrollView);
  Vue.component("WebView", WebView);
  Vue.component("Frame", Frame);
  Vue.component("SearchBar", SearchBar);
  Vue.component("SegmentedBar", SegmentedBar);
  Vue.component("SegmentedBarItem", SegmentedBarItem);
  Vue.component("Slider", Slider);
  Vue.component("Switcher", Switcher);
  Vue.component("TextField", TextField);
  Vue.component("TextView", TextView);
  Vue.component("Span", Span);
  Vue.component("FormattedString", FormattedString);
  Vue.component("ActionItem", ActionItem);
  Vue.component("NavigationButton", NavigationButton);
  Vue.component("ActionBar", ActionBar);
  Vue.component("TabView", TabView);
  Vue.component("TabViewItem", TabViewItem);
  Vue.component("ActionDialog", ActionDialog);
  Vue.component("AlertDialog", AlertDialog);
  Vue.component("ConfirmDialog", ConfirmDialog);
  Vue.component("AbsoluteLayout", AbsoluteLayout);
  Vue.component("StackLayout", StackLayout);
  Vue.component("DockLayout", DockLayout);
  Vue.component("FlexboxLayout", FlexboxLayout);
  Vue.component("GridLayout", GridLayout);
  Vue.component("WrapLayout", WrapLayout);

  Vue.component("VxpButton", VxpButton);
  Vue.component("VxpCheckbox", VxpCheckbox);
  Vue.component("VxpDatePicker", VxpDatePicker);
  Vue.component("VxpDropDown", VxpDropDown);
  Vue.component("VxpDropDown2", VxpDropDown2);
  Vue.component("VxpIconButton", VxpIconButton);
  Vue.component("VxpImage", VxpImage);
  Vue.component("VxpLabel", VxpLabel);
  Vue.component("VxpLink", VxpLink);
  Vue.component("VxpListView", VxpListView);
  Vue.component("VxpMultiSelectDropdown", VxpMultiSelectDropdown);
  Vue.component("VxpTableView", VxpTableView);
  Vue.component("VxpTextField", VxpTextField);
  Vue.component("VxpSideDrawer", VxpSideDrawer);
  Vue.component("VxpDropdownMenu", VxpDropdownMenu);
}
