version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: npm install
      - run: npm i nativescript
      - run: npm -- run setup-webpack-config && tns build android --bundle --env.production && npm run remove-webpack-config
