version: 2

default_config: &default_config
  working_directory: ~/circleci/tns-circleci-example
  docker:
    - image: circleci/node:11
  environment:
    ANDROID_HOME: '/usr/local/share/android-sdk'

jobs:
  build:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: Fetch CocoaPods repository
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            # Fetch cocoapods specs from S3 instead of github

      - restore_cache:
          key: npm-cache-{{ checksum "./package-lock.json" }}
      - run:
          name: 'Install node dependencies'
          command: |
            npm install
            npx tns usage-reporting disable
            npx tns error-reporting disable
      - save_cache:
          key: npm-cache-{{ checksum "./package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: 'Rebuild Node SASS bindings'
          command: npm rebuild node-sass --force
      - run:
          name: 'Prepare Android'
          command: npx tns prepare android
      - run:
          name: 'Build Android'
          command: |
            ./scripts/build_android.sh
      - persist_to_workspace:
          root: ~/circleci
          paths:
            - tns-circleci-example
  deploy:
    <<: *default_config
    steps:
      - attach_workspace:
          at: ~/circleci
      - run:
          name: 'Deploy'
          command: |
            npx tns usage-reporting disable
            npx tns error-reporting disable
            ./scripts/deploy.sh
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
